FROM mysql:latest

# Variables de entorno
ENV MYSQL_ROOT_PASSWORD=pbd1
ENV MYSQL_DATABASE=pbd1

# Archivo SQL al contenedor
COPY base.sql /docker-entrypoint-initdb.d/

# Script de Pythonr
COPY cargado.py /cargado.py

EXPOSE 3306

# docker build -t pbd1 .

# docker run -d -p 4200:3306 --name pbd1 pbd1  


# docker run -d -p 4200:3306 -v ./init:/docker-entrypoint-initdb.d/:ro -e MYSQL_ROOT_PASSWORD=pbd1 -e MYSQL_DATABASE=pbd1 --name pbd1 mysql:latest
